Oops
In hindsight I should've just replaced charizard or something's backsprite with a 48x48 for this.
But, may as well see if you can fix this too, right?

Gen 1 backsprites are 32x32, but due to how the scaling works, in practice it's 28x28 pixels.
Gen 2 backsprites, including in Spaceworld 1997, they are a presumably-uncompressed 48x48.

Gen 1 supports front sprites that are 40x40 (5x5-tiles), 48x48 (6x6 tiles), or 56x56 (7x7 tiles). However, it and Gen 2 only support one size for Backsprite.

I want you to see if you can make it so Yellow can support both its original 32x32 (28x28), as well as 48x48.

Here is some links that may be useful for that.
https://github.com/pret/pokered/wiki/Adding-a-New-Pokemon
(the part about adding base stats involves sprite dimensions)

https://github.com/pret/pokered/wiki/Back-Sprites-48x48-(Like-GEN-2)
(there's a tutorial for replacing the 32x32 with uncompressed 48x48, but I want to be able to use both.)

--

HOWEVER, while doing this, I hit a roadblock.
The ROM won't compile because of something it says is in Layout.link.
Here's the error code in WSL.

error: Cannot decrease the current address (from $df17 to $df15)
    at layout.link(243)
error: The linker script assigns section "Stack" to address $df17, but then it would overflow WRAM0 by 2 bytes
    at layout.link(244)
Linking failed with 2 errors
make: *** [Makefile:147: pokeyellow.gbc] Error 1

So someone has to fix that first. I'm not sure how.

Here's the tutorials I used to add what somehow caused this.

"Free some space in BANK 1E"
https://github.com/pret/pokeyellow/wiki/Free-some-space-in-BANK-1E

"Free some space in the Home BANK"
https://github.com/pret/pokeyellow/wiki/Free-some-space-in-the-Home-BANK

I added the types Dark, Steel, and Pink.
I added Pinkachu's data.
He has his 48x48 backsprite, it'll look like a mess until you do this.
(I added him for the purpose of experimenting with 48x48 backsprite. In hindsight I could've just replaced any current mon's backsprite, but whatever.)
Pinkachu's signature move, Paz Yppiz, required a better move priority system.
https://github.com/pret/pokered/wiki/Implement-move-priority-system